In [30]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import openpyxl

In [57]:
url='https://www.numbeo.com/crime/rankings_by_country.jsp?title=2021&region=150'
req=requests.get(url)
content=req.text


soup = BeautifulSoup(content, features="html.parser")

#for child in soup.descendants:
#    if child.name:
#        print(child.name)
#        print(soup.td)

#print(soup.tr)
#layer_1 = soup.find_all('div', attrs={'class': 'innerWidth'})
layer_1 = soup.find_all('table', attrs={'id': 't2'})
#layer_1 = soup.find_all('td', attrs={'class': 'cityOrCountryInIndicesTable'}) #Gets a list of all Countries
#print(layer_1[0].text)
text_with_empty_lines = layer_1[0].text
lines = text_with_empty_lines.split('\n')
text_with_non_empty_lines = [line for line in lines if line.strip() != ""]

print(text_with_non_empty_lines)

['Rank', 'Country', 'Crime Index', 'Safety Index', 'Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']

In [58]:
new_list = []

def cut_list(list):
    for i in range(4):
        list.pop(0)
        #new_list = list
    print(list)
        #new_list = list
    return list

def split_list(list):
    if((len(list))%3==0):
        print("Divisible by 3")
    else:
        print("List size not divisible by 3")

new_list = cut_list(text_with_non_empty_lines)

['Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']

In [59]:
n=3
country_crime_list = [x for i, x in enumerate(new_list) if i%n !=2]
country_crime_tuple_list = [x for x in zip(*[iter(country_crime_list)]*2)]
print(country_crime_tuple_list)

[('Belarus', '60.27'), ('France', '49.20'), ('Ukraine', '48.28'), ('Sweden', '47.20'), ('Moldova', '46.56'), ('United Kingdom', '45.26'), ('Ireland', '45.02'), ('Italy', '44.37'), ('Belgium', '44.17'), ('Greece', '44.14'), ('Bosnia And Herzegovina', '43.01'), ('Albania', '41.64'), ('Montenegro', '41.61'), ('Russia', '40.13'), ('Malta', '38.93'), ('North Macedonia', '38.59'), ('Serbia', '38.26'), ('Bulgaria', '38.12'), ('Latvia', '37.21'), ('Kosovo (Disputed Territory)', '36.12'), ('Germany', '35.42'), ('Hungary', '34.81'), ('Lithuania', '33.84'), ('Norway', '33.35'), ('Spain', '33.13'), ('Luxembourg', '32.15'), ('Portugal', '29.89'), ('Slovakia', '29.74'), ('Poland', '29.32'), ('Romania', '28.35'), ('Netherlands', '27.22'), ('Finland', '27.01'), ('Denmark', '26.72'), ('Czech Republic', '25.31'), ('Austria', '25.23'), ('Croatia', '24.91'), ('Iceland', '24.13'), ('Estonia', '23.38'), ('Slovenia', '21.79'), ('Switzerland', '21.35'), ('Isle Of Man', '20.79')]

In [60]:
df = pd.DataFrame(country_crime_tuple_list, columns =['Country', 'Crime_Index'])
df

                        Country Crime_Index
0                       Belarus       60.27
1                        France       49.20
2                       Ukraine       48.28
3                        Sweden       47.20
4                       Moldova       46.56
5                United Kingdom       45.26
6                       Ireland       45.02
7                         Italy       44.37
8                       Belgium       44.17
9                        Greece       44.14
10       Bosnia And Herzegovina       43.01
11                      Albania       41.64
12                   Montenegro       41.61
13                       Russia       40.13
14                        Malta       38.93
15              North Macedonia       38.59
16                       Serbia       38.26
17                     Bulgaria       38.12
18                       Latvia       37.21
19  Kosovo (Disputed Territory)       36.12
20                      Germany       35.42
21                      Hungary       34.81
22                    Lithuania       33.84
23                       Norway       33.35
24                        Spain       33.13
25                   Luxembourg       32.15
26                     Portugal       29.89
27                     Slovakia       29.74
28                       Poland       29.32
29                      Romania       28.35
30                  Netherlands       27.22
31                      Finland       27.01
32                      Denmark       26.72
33               Czech Republic       25.31
34                      Austria       25.23
35                      Croatia       24.91
36                      Iceland       24.13
37                      Estonia       23.38
38                     Slovenia       21.79
39                  Switzerland       21.35
40                  Isle Of Man       20.79

In [62]:
#dictlist = dict(country_crime_tuple_list)
#dictlist


result = {}

for (key, value) in country_crime_tuple_list:
    #setting the default value as list([])
    #appending the current value
    result.setdefault(key, []).append(value)

print(result)

#for (key, value) in country_crime_tuple_list:
#    setting the default value as list([])
#    appending the current value
#    result.setdefault(key, []).append(value)
    
#print(result)

data_items = result.items()
data_list = list(data_items)

#df = pd.DataFrame(data_list)
data_list

#df = pd.DataFrame(data_list, columns =['Country', 'Crime_Index'])
#df[['2021','2020']] = pd.DataFrame(df['Crime_Index'].to_list(), columns = ['c1', 'c2'])
#df = df.drop("Crime_Index", axis=1)
#df

{'Belarus': ['60.27'], 'France': ['49.20'], 'Ukraine': ['48.28'], 'Sweden': ['47.20'], 'Moldova': ['46.56'], 'United Kingdom': ['45.26'], 'Ireland': ['45.02'], 'Italy': ['44.37'], 'Belgium': ['44.17'], 'Greece': ['44.14'], 'Bosnia And Herzegovina': ['43.01'], 'Albania': ['41.64'], 'Montenegro': ['41.61'], 'Russia': ['40.13'], 'Malta': ['38.93'], 'North Macedonia': ['38.59'], 'Serbia': ['38.26'], 'Bulgaria': ['38.12'], 'Latvia': ['37.21'], 'Kosovo (Disputed Territory)': ['36.12'], 'Germany': ['35.42'], 'Hungary': ['34.81'], 'Lithuania': ['33.84'], 'Norway': ['33.35'], 'Spain': ['33.13'], 'Luxembourg': ['32.15'], 'Portugal': ['29.89'], 'Slovakia': ['29.74'], 'Poland': ['29.32'], 'Romania': ['28.35'], 'Netherlands': ['27.22'], 'Finland': ['27.01'], 'Denmark': ['26.72'], 'Czech Republic': ['25.31'], 'Austria': ['25.23'], 'Croatia': ['24.91'], 'Iceland': ['24.13'], 'Estonia': ['23.38'], 'Slovenia': ['21.79'], 'Switzerland': ['21.35'], 'Isle Of Man': ['20.79']}

[('Belarus', ['60.27']),
 ('France', ['49.20']),
 ('Ukraine', ['48.28']),
 ('Sweden', ['47.20']),
 ('Moldova', ['46.56']),
 ('United Kingdom', ['45.26']),
 ('Ireland', ['45.02']),
 ('Italy', ['44.37']),
 ('Belgium', ['44.17']),
 ('Greece', ['44.14']),
 ('Bosnia And Herzegovina', ['43.01']),
 ('Albania', ['41.64']),
 ('Montenegro', ['41.61']),
 ('Russia', ['40.13']),
 ('Malta', ['38.93']),
 ('North Macedonia', ['38.59']),
 ('Serbia', ['38.26']),
 ('Bulgaria', ['38.12']),
 ('Latvia', ['37.21']),
 ('Kosovo (Disputed Territory)', ['36.12']),
 ('Germany', ['35.42']),
 ('Hungary', ['34.81']),
 ('Lithuania', ['33.84']),
 ('Norway', ['33.35']),
 ('Spain', ['33.13']),
 ('Luxembourg', ['32.15']),
 ('Portugal', ['29.89']),
 ('Slovakia', ['29.74']),
 ('Poland', ['29.32']),
 ('Romania', ['28.35']),
 ('Netherlands', ['27.22']),
 ('Finland', ['27.01']),
 ('Denmark', ['26.72']),
 ('Czech Republic', ['25.31']),
 ('Austria', ['25.23']),
 ('Croatia', ['24.91']),
 ('Iceland', ['24.13']),
 ('Estonia', ['23.38']),
 ('Slovenia', ['21.79']),
 ('Switzerland', ['21.35']),
 ('Isle Of Man', ['20.79'])]

In [ ]:
country_list = []
def country_split(list):
    country_list = list[::3]
    print(country_list)

crime_index_list = []
def crime_index_split(list):
    list.pop(0)
    crime_index_list = list[::3]
    print(crime_index_list)

new_list = cut_list(text_with_non_empty_lines)

#split_list(new_list)
#print(new_list)
#country_split(new_list)
#crime_index_split(new_list)

In [95]:
#new_list = []

def cut_list(list):
    for i in range(4):
        list.pop(0)
    return list

def split_list(list):
    if((len(list))%3==0):
        print("Divisible by 3")
        n=3
        country_crime_list = [x for i, x in enumerate(list) if i%n !=2]
        country_crime_tuple_list = [x for x in zip(*[iter(country_crime_list)]*2)]
        #print(country_crime_tuple_list)
        return country_crime_tuple_list
    else:
        print("List size not divisible by 3")

def format_data(data):
    data1 = []
    print('DATA1:',data)
    data1 = cut_list(data)
    print('DATA2:',data1)
    data1 = split_list(data1)
    print('DATA3:',data1)
    
    data2 = []
    
    
    return data1

#def slice_and_combine():
#    



def slicer(DATA3,DATA3_2):
    result = {}
    for (key, value) in DATA3:
        result.setdefault(key, []).append(value)
    print(result)

    for (key, value) in DATA3_2:
        result.setdefault(key, []).append(value)
    print(result)
    return result

#data_items = result.items()
#data_list = list(data_items)

#df = pd.DataFrame(data_list)
#data_list















def create_dataframe(data):
    df = pd.DataFrame(data, columns =['Country', 'Crime_Index'])
    return df
    
def get_df(url,url2):
    #print('Returned Data:', text_with_non_empty_lines)
    formatted_data = format_data(get_data(url))
    formatted_data2 = format_data(get_data(url2))
    #create_dataframe(formatted_data)
    #return format_data(text_with_non_empty_lines)
    return create_dataframe(formatted_data), create_dataframe(formatted_data2)
      
def get_data(url):
    current_url = url
    req         = requests.get(current_url)
    content     = req.text
    soup        = BeautifulSoup(content, features="html.parser")
    layer_1     = soup.find_all('table', attrs={'id': 't2'})
    text_with_empty_lines = layer_1[0].text
    lines       = text_with_empty_lines.split('\n')
    text_with_non_empty_lines = [line for line in lines if line.strip() != ""]
    return text_with_non_empty_lines

In [96]:
get_df('https://www.numbeo.com/crime/rankings_by_country.jsp?title=2021&region=150','https://www.numbeo.com/crime/rankings_by_country.jsp?title=2021&region=150')

DATA1: ['Rank', 'Country', 'Crime Index', 'Safety Index', 'Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']
DATA2: ['Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']
Divisible by 3
DATA3: [('Belarus', '60.27'), ('France', '49.20'), ('Ukraine', '48.28'), ('Sweden', '47.20'), ('Moldova', '46.56'), ('United Kingdom', '45.26'), ('Ireland', '45.02'), ('Italy', '44.37'), ('Belgium', '44.17'), ('Greece', '44.14'), ('Bosnia And Herzegovina', '43.01'), ('Albania', '41.64'), ('Montenegro', '41.61'), ('Russia', '40.13'), ('Malta', '38.93'), ('North Macedonia', '38.59'), ('Serbia', '38.26'), ('Bulgaria', '38.12'), ('Latvia', '37.21'), ('Kosovo (Disputed Territory)', '36.12'), ('Germany', '35.42'), ('Hungary', '34.81'), ('Lithuania', '33.84'), ('Norway', '33.35'), ('Spain', '33.13'), ('Luxembourg', '32.15'), ('Portugal', '29.89'), ('Slovakia', '29.74'), ('Poland', '29.32'), ('Romania', '28.35'), ('Netherlands', '27.22'), ('Finland', '27.01'), ('Denmark', '26.72'), ('Czech Republic', '25.31'), ('Austria', '25.23'), ('Croatia', '24.91'), ('Iceland', '24.13'), ('Estonia', '23.38'), ('Slovenia', '21.79'), ('Switzerland', '21.35'), ('Isle Of Man', '20.79')]
DATA1: ['Rank', 'Country', 'Crime Index', 'Safety Index', 'Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']
DATA2: ['Belarus', '60.27', '39.73', 'France', '49.20', '50.80', 'Ukraine', '48.28', '51.72', 'Sweden', '47.20', '52.80', 'Moldova', '46.56', '53.44', 'United Kingdom', '45.26', '54.74', 'Ireland', '45.02', '54.98', 'Italy', '44.37', '55.63', 'Belgium', '44.17', '55.83', 'Greece', '44.14', '55.86', 'Bosnia And Herzegovina', '43.01', '56.99', 'Albania', '41.64', '58.36', 'Montenegro', '41.61', '58.39', 'Russia', '40.13', '59.87', 'Malta', '38.93', '61.07', 'North Macedonia', '38.59', '61.41', 'Serbia', '38.26', '61.74', 'Bulgaria', '38.12', '61.88', 'Latvia', '37.21', '62.79', 'Kosovo (Disputed Territory)', '36.12', '63.88', 'Germany', '35.42', '64.58', 'Hungary', '34.81', '65.19', 'Lithuania', '33.84', '66.16', 'Norway', '33.35', '66.65', 'Spain', '33.13', '66.87', 'Luxembourg', '32.15', '67.85', 'Portugal', '29.89', '70.11', 'Slovakia', '29.74', '70.26', 'Poland', '29.32', '70.68', 'Romania', '28.35', '71.65', 'Netherlands', '27.22', '72.78', 'Finland', '27.01', '72.99', 'Denmark', '26.72', '73.28', 'Czech Republic', '25.31', '74.69', 'Austria', '25.23', '74.77', 'Croatia', '24.91', '75.09', 'Iceland', '24.13', '75.87', 'Estonia', '23.38', '76.62', 'Slovenia', '21.79', '78.21', 'Switzerland', '21.35', '78.65', 'Isle Of Man', '20.79', '79.21']
Divisible by 3
DATA3: [('Belarus', '60.27'), ('France', '49.20'), ('Ukraine', '48.28'), ('Sweden', '47.20'), ('Moldova', '46.56'), ('United Kingdom', '45.26'), ('Ireland', '45.02'), ('Italy', '44.37'), ('Belgium', '44.17'), ('Greece', '44.14'), ('Bosnia And Herzegovina', '43.01'), ('Albania', '41.64'), ('Montenegro', '41.61'), ('Russia', '40.13'), ('Malta', '38.93'), ('North Macedonia', '38.59'), ('Serbia', '38.26'), ('Bulgaria', '38.12'), ('Latvia', '37.21'), ('Kosovo (Disputed Territory)', '36.12'), ('Germany', '35.42'), ('Hungary', '34.81'), ('Lithuania', '33.84'), ('Norway', '33.35'), ('Spain', '33.13'), ('Luxembourg', '32.15'), ('Portugal', '29.89'), ('Slovakia', '29.74'), ('Poland', '29.32'), ('Romania', '28.35'), ('Netherlands', '27.22'), ('Finland', '27.01'), ('Denmark', '26.72'), ('Czech Republic', '25.31'), ('Austria', '25.23'), ('Croatia', '24.91'), ('Iceland', '24.13'), ('Estonia', '23.38'), ('Slovenia', '21.79'), ('Switzerland', '21.35'), ('Isle Of Man', '20.79')]

AttributeError: 'list' object has no attribute 'items'

In [23]:
#new_list = []

def cut_list(list):
    for i in range(4):
        list.pop(0)
    return list

def split_list(list):
    if((len(list))%3==0):
        print("Divisible by 3")
        n=3
        country_crime_list = [x for i, x in enumerate(list) if i%n !=2]
        country_crime_tuple_list = [x for x in zip(*[iter(country_crime_list)]*2)]
        #print(country_crime_tuple_list)
        return country_crime_tuple_list
    else:
        print("List size not divisible by 3")

def format_data(list_of_urls):
    sliced_list = []
    for url in list_of_urls:
        sliced_list.append(slice_and_combine(url))
    return super_slicer(sliced_list)


#def format_data(data_1,data_2):
#    data1 = slice_and_combine(data_1)
#    data2 = slice_and_combine(data_2)
#    return super_slicer(data1,data2)

def slice_and_combine(data):
    data_list = []
    data_list = cut_list(data)
    data_list = split_list(data_list)
    return data_list



def super_slicer(sliced_list):
    result = {}
    for list in sliced_list:
        for (key, value) in list:
            result.setdefault(key, []).append(value)
        #print(result)
    return result

#data_items = result.items()
#data_list = list(data_items)

#df = pd.DataFrame(data_list)
#data_list

#def super_slicer(sliced_list):

#        result = {}
#        for (key, value) in DATA3:
#            result.setdefault(key, []).append(value)
##        print(result)
#
#        for (key, value) in DATA3_2:
#            result.setdefault(key, []).append(value)
#        #print(result)
#        return result

#data_items = result.items()
#data_list = list(data_items)

#df = pd.DataFrame(data_list)
#data_list













def create_dataframe(data):
    data_items = data.items()
    data_list = list(data_items)
    df = pd.DataFrame(data_list, columns =['Country', 'Crime_Index'])
    df[['2021',
        '2020',
        '2019',
        '2018',
        '2017',
        '2016',
        '2015',
        '2014']] = pd.DataFrame(df['Crime_Index'].to_list())
    df = df.drop("Crime_Index", axis=1)
    #df
    
    #df = pd.DataFrame(data, columns =['Country', 'Crime_Index'])
    return df
    
    
def get_df(list_of_urls):
    #print('Returned Data:', text_with_non_empty_lines)
    newList = []
    for list in list_of_urls:
        newList.append(get_data(list))
    formatted_data = format_data(newList)
    #create_dataframe(formatted_data)
    #return format_data(text_with_non_empty_lines)
    return create_dataframe(formatted_data)
      
def get_data(url):
    current_url = url
    req         = requests.get(current_url)
    content     = req.text
    soup        = BeautifulSoup(content, features="html.parser")
    layer_1     = soup.find_all('table', attrs={'id': 't2'})
    text_with_empty_lines = layer_1[0].text
    lines       = text_with_empty_lines.split('\n')
    text_with_non_empty_lines = [line for line in lines if line.strip() != ""]
    return text_with_non_empty_lines

In [25]:
websites = []
websites = ['https://www.numbeo.com/crime/rankings_by_country.jsp?title=2021&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2020&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2019&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2018&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2017&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2016&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2015&region=150',
            'https://www.numbeo.com/crime/rankings_by_country.jsp?title=2014&region=150']

df = get_df(websites)
df

Divisible by 3
Divisible by 3
Divisible by 3
Divisible by 3
Divisible by 3
Divisible by 3
Divisible by 3
Divisible by 3

,Country,2021,2020,2019,2018,2017,2016,2015,2014
0,Belarus,60.27,24.99,23.53,26.55,22.26,27.57,30.50,32.89
1,France,49.20,46.79,46.39,45.29,43.66,44.06,49.71,47.28
2,Ukraine,48.28,48.85,48.88,49.39,51.27,48.62,49.36,49.37
3,Sweden,47.20,47.07,49.35,49.26,46.65,43.12,42.09,38.28
4,Moldova,46.56,44.98,45.45,45.66,45.35,48.16,49.70,46.32
5,United Kingdom,45.26,43.71,42.72,41.20,41.19,43.13,42.01,42.62
6,Ireland,45.02,45.43,44.52,43.82,45.77,48.39,49.07,53.59
7,Italy,44.37,44.26,45.02,44.53,44.66,46.22,47.50,45.59
8,Belgium,44.17,43.98,42.46,42.17,44.51,45.19,42.04,41.53
9,Greece,44.14,40.32,38.57,39.07,40.32,38.46,41.35,43.05
10,Bosnia And Herzegovina,43.01,43.03,43.79,40.05,40.97,42.46,45.82,44.98
11,Albania,41.64,39.52,40.30,39.87,44.27,48.15,49.60,51.31
12,Montenegro,41.61,41.18,40.48,37.51,38.67,47.80,34.89,None
13,Russia,40.13,41.12,41.93,45.20,46.05,47.31,51.33,52.67
14,Malta,38.93,39.04,33.53,31.93,30.56,26.73,25.91,14.17
15,North Macedonia,38.59,38.67,39.29,40.21,38.66,38.02,36.06,41.67
16,Serbia,38.26,37.41,37.27,37.76,38.62,43.28,43.43,39.28
17,Bulgaria,38.12,38.50,40.00,39.70,40.18,41.42,43.45,40.02
18,Latvia,37.21,36.95,36.77,36.89,36.45,37.79,37.22,43.74
19,Kosovo (Disputed Territory),36.12,32.91,46.76,None,None,None,None,None
20,Germany,35.42,34.81,34.51,36.65,32.03,32.95,28.49,27.14
21,Hungary,34.81,35.08,35.17,36.51,38.39,41.93,41.76,37.52
22,Lithuania,33.84,33.06,36.51,37.59,40.03,43.15,36.69,34.71
23,Norway,33.35,35.43,35.32,43.33,45.69,30.11,31.19,33.73
24,Spain,33.13,31.96,32.46,36.74,31.28,31.77,33.85,32.42
25,Luxembourg,32.15,33.39,29.07,32.12,29.04,36.03,35.74,31.88
26,Portugal,29.89,29.63,32.13,34.54,35.39,35.13,35.84,35.06
27,Slovakia,29.74,29.22,29.54,30.15,30.18,33.49,33.34,32.72
28,Poland,29.32,28.50,30.09,36.23,31.53,31.41,32.99,37.53
29,Romania,28.35,27.64,27.84,29.04,27.95,29.72,29.72,28.73
30,Netherlands,27.22,27.62,28.57,28.94,29.89,31.47,35.41,37.07
31,Finland,27.01,23.32,22.80,23.70,24.63,28.12,29.55,29.16
32,Denmark,26.72,25.10,24.25,22.02,21.13,25.67,25.71,29.27
33,Czech Republic,25.31,25.52,26.66,28.81,30.18,32.06,32.89,33.88
34,Austria,25.23,23.73,21.37,20.41,19.25,24.06,26.25,25.83
35,Croatia,24.91,24.71,24.69,27.00,27.80,29.51,29.34,28.90
36,Iceland,24.13,23.36,23.28,24.49,27.49,29.89,33.32,31.68
37,Estonia,23.38,23.14,20.80,20.83,23.00,24.67,28.13,29.07
38,Slovenia,21.79,21.07,22.57,24.71,24.05,26.27,28.71,33.21
39,Switzerland,21.35,21.60,21.50,21.76,22.45,25.73,26.77,31.79
40,Isle Of Man,20.79,15.10,16.95,None,None,None,None,None
41,Monaco,27.94,29.01,None,None,None,None,None,None
42,Faroe Islands,18.53,None,None,None,None,None,None,None

In [26]:
newdf = df.dropna()
newdf

,Country,2021,2020,2019,2018,2017,2016,2015,2014
0,Belarus,60.27,24.99,23.53,26.55,22.26,27.57,30.50,32.89
1,France,49.20,46.79,46.39,45.29,43.66,44.06,49.71,47.28
2,Ukraine,48.28,48.85,48.88,49.39,51.27,48.62,49.36,49.37
3,Sweden,47.20,47.07,49.35,49.26,46.65,43.12,42.09,38.28
4,Moldova,46.56,44.98,45.45,45.66,45.35,48.16,49.70,46.32
5,United Kingdom,45.26,43.71,42.72,41.20,41.19,43.13,42.01,42.62
6,Ireland,45.02,45.43,44.52,43.82,45.77,48.39,49.07,53.59
7,Italy,44.37,44.26,45.02,44.53,44.66,46.22,47.50,45.59
8,Belgium,44.17,43.98,42.46,42.17,44.51,45.19,42.04,41.53
9,Greece,44.14,40.32,38.57,39.07,40.32,38.46,41.35,43.05
10,Bosnia And Herzegovina,43.01,43.03,43.79,40.05,40.97,42.46,45.82,44.98
11,Albania,41.64,39.52,40.30,39.87,44.27,48.15,49.60,51.31
13,Russia,40.13,41.12,41.93,45.20,46.05,47.31,51.33,52.67
14,Malta,38.93,39.04,33.53,31.93,30.56,26.73,25.91,14.17
15,North Macedonia,38.59,38.67,39.29,40.21,38.66,38.02,36.06,41.67
16,Serbia,38.26,37.41,37.27,37.76,38.62,43.28,43.43,39.28
17,Bulgaria,38.12,38.50,40.00,39.70,40.18,41.42,43.45,40.02
18,Latvia,37.21,36.95,36.77,36.89,36.45,37.79,37.22,43.74
20,Germany,35.42,34.81,34.51,36.65,32.03,32.95,28.49,27.14
21,Hungary,34.81,35.08,35.17,36.51,38.39,41.93,41.76,37.52
22,Lithuania,33.84,33.06,36.51,37.59,40.03,43.15,36.69,34.71
23,Norway,33.35,35.43,35.32,43.33,45.69,30.11,31.19,33.73
24,Spain,33.13,31.96,32.46,36.74,31.28,31.77,33.85,32.42
25,Luxembourg,32.15,33.39,29.07,32.12,29.04,36.03,35.74,31.88
26,Portugal,29.89,29.63,32.13,34.54,35.39,35.13,35.84,35.06
27,Slovakia,29.74,29.22,29.54,30.15,30.18,33.49,33.34,32.72
28,Poland,29.32,28.50,30.09,36.23,31.53,31.41,32.99,37.53
29,Romania,28.35,27.64,27.84,29.04,27.95,29.72,29.72,28.73
30,Netherlands,27.22,27.62,28.57,28.94,29.89,31.47,35.41,37.07
31,Finland,27.01,23.32,22.80,23.70,24.63,28.12,29.55,29.16
32,Denmark,26.72,25.10,24.25,22.02,21.13,25.67,25.71,29.27
33,Czech Republic,25.31,25.52,26.66,28.81,30.18,32.06,32.89,33.88
34,Austria,25.23,23.73,21.37,20.41,19.25,24.06,26.25,25.83
35,Croatia,24.91,24.71,24.69,27.00,27.80,29.51,29.34,28.90
36,Iceland,24.13,23.36,23.28,24.49,27.49,29.89,33.32,31.68
37,Estonia,23.38,23.14,20.80,20.83,23.00,24.67,28.13,29.07
38,Slovenia,21.79,21.07,22.57,24.71,24.05,26.27,28.71,33.21
39,Switzerland,21.35,21.60,21.50,21.76,22.45,25.73,26.77,31.79

In [27]:
newdf.to_csv(index=False)

'Country,2021,2020,2019,2018,2017,2016,2015,2014\r\nBelarus,60.27,24.99,23.53,26.55,22.26,27.57,30.50,32.89\r\nFrance,49.20,46.79,46.39,45.29,43.66,44.06,49.71,47.28\r\nUkraine,48.28,48.85,48.88,49.39,51.27,48.62,49.36,49.37\r\nSweden,47.20,47.07,49.35,49.26,46.65,43.12,42.09,38.28\r\nMoldova,46.56,44.98,45.45,45.66,45.35,48.16,49.70,46.32\r\nUnited Kingdom,45.26,43.71,42.72,41.20,41.19,43.13,42.01,42.62\r\nIreland,45.02,45.43,44.52,43.82,45.77,48.39,49.07,53.59\r\nItaly,44.37,44.26,45.02,44.53,44.66,46.22,47.50,45.59\r\nBelgium,44.17,43.98,42.46,42.17,44.51,45.19,42.04,41.53\r\nGreece,44.14,40.32,38.57,39.07,40.32,38.46,41.35,43.05\r\nBosnia And Herzegovina,43.01,43.03,43.79,40.05,40.97,42.46,45.82,44.98\r\nAlbania,41.64,39.52,40.30,39.87,44.27,48.15,49.60,51.31\r\nRussia,40.13,41.12,41.93,45.20,46.05,47.31,51.33,52.67\r\nMalta,38.93,39.04,33.53,31.93,30.56,26.73,25.91,14.17\r\nNorth Macedonia,38.59,38.67,39.29,40.21,38.66,38.02,36.06,41.67\r\nSerbia,38.26,37.41,37.27,37.76,38.62,43.28,43.43,39.28\r\nBulgaria,38.12,38.50,40.00,39.70,40.18,41.42,43.45,40.02\r\nLatvia,37.21,36.95,36.77,36.89,36.45,37.79,37.22,43.74\r\nGermany,35.42,34.81,34.51,36.65,32.03,32.95,28.49,27.14\r\nHungary,34.81,35.08,35.17,36.51,38.39,41.93,41.76,37.52\r\nLithuania,33.84,33.06,36.51,37.59,40.03,43.15,36.69,34.71\r\nNorway,33.35,35.43,35.32,43.33,45.69,30.11,31.19,33.73\r\nSpain,33.13,31.96,32.46,36.74,31.28,31.77,33.85,32.42\r\nLuxembourg,32.15,33.39,29.07,32.12,29.04,36.03,35.74,31.88\r\nPortugal,29.89,29.63,32.13,34.54,35.39,35.13,35.84,35.06\r\nSlovakia,29.74,29.22,29.54,30.15,30.18,33.49,33.34,32.72\r\nPoland,29.32,28.50,30.09,36.23,31.53,31.41,32.99,37.53\r\nRomania,28.35,27.64,27.84,29.04,27.95,29.72,29.72,28.73\r\nNetherlands,27.22,27.62,28.57,28.94,29.89,31.47,35.41,37.07\r\nFinland,27.01,23.32,22.80,23.70,24.63,28.12,29.55,29.16\r\nDenmark,26.72,25.10,24.25,22.02,21.13,25.67,25.71,29.27\r\nCzech Republic,25.31,25.52,26.66,28.81,30.18,32.06,32.89,33.88\r\nAustria,25.23,23.73,21.37,20.41,19.25,24.06,26.25,25.83\r\nCroatia,24.91,24.71,24.69,27.00,27.80,29.51,29.34,28.90\r\nIceland,24.13,23.36,23.28,24.49,27.49,29.89,33.32,31.68\r\nEstonia,23.38,23.14,20.80,20.83,23.00,24.67,28.13,29.07\r\nSlovenia,21.79,21.07,22.57,24.71,24.05,26.27,28.71,33.21\r\nSwitzerland,21.35,21.60,21.50,21.76,22.45,25.73,26.77,31.79\r\n'

In [31]:
newdf.to_excel("CrimeIndex.xlsx", sheet_name='Data')

In [29]:
pip install openpyxl

Collecting openpyxlNote: you may need to restart the kernel to use updated packages.
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting et-xmlfile

  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9